package criptografia;

/**
* criptografia/CifraCesarHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cesar.idl
* Sexta-feira, 28 de Novembro de 2014 11h54min14s GFT
*/

public final class CifraCesarHolder implements org.omg.CORBA.portable.Streamable
{
  public criptografia.CifraCesar value = null;

  public CifraCesarHolder ()
  {
  }

  public CifraCesarHolder (criptografia.CifraCesar initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = criptografia.CifraCesarHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    criptografia.CifraCesarHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return criptografia.CifraCesarHelper.type ();
  }

}
