package criptografia;


/**
* criptografia/CifraCesarOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cesar.idl
* Sexta-feira, 28 de Novembro de 2014 11h54min14s GFT
*/

public interface CifraCesarOperations 
{
  String encript (String frase, float chave);
  String decript (String frase, float chave);
  void shutdown ();
} // interface CifraCesarOperations
