package criptografia;


/**
* criptografia/CifraCesar.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cesar.idl
* Sexta-feira, 28 de Novembro de 2014 11h54min14s GFT
*/

public interface CifraCesar extends CifraCesarOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CifraCesar
